services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.build
    container_name: builder
    # We mount our local project code into /src so the container sees it
    volumes:
      - .:/src
    command: ["make", "all"]

  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT_MODE: legacy
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu/os.iso:/boot.iso
    restart: always
    stop_grace_period: 2m
